### ISSUE TITLE
UI difference while Compare the background of web auth from figma 

### ISSUE THREAD

**Issue by sanilnayak** [sparrowapp-dev/sparrow-app-auth#16]
### **🐛 Bug Report**

UI difference while Compare the background of web auth from figma

**Steps to reproduce:**

- Launch the sparrow app and click on "create account or sign IN"
-User will navigate to web auth now see the background 

**Expected Behaviour:** background should be according to figma 

<img width="702" alt="Screenshot 2024-02-27 at 12 54 32 PM" src="https://github.com/sparrowapp-dev/sparrow-app-auth/assets/129532962/d141e03b-9a14-4c2e-82a3-0af3744f2e5e">

**Actual Behaviour:** Background colour is all black but in figma its not (in lower side there is some colour gradient)

<img width="1710" alt="Screenshot 2024-02-27 at 12 57 07 PM" src="https://github.com/sparrowapp-dev/sparrow-app-auth/assets/129532962/83160201-f75a-4e5d-9c23-7f7b925ffb44">

**Comment by sanilnayak** [comment]
Fixed @rahulparmarQA please check

**Comment by rahulparmarQA** [comment]
fixed
